export const UPDATE_USERTEXT = 'UPDATE_USERTEXT';
export const TOGGLE_PRACTICE = 'TOGGLE_PRACTICE';
export const UPDATE_PRACTICE_QUESTIONS = 'UPDATE_PRACTICE_QUESTIONS';
export const UPDATE_Q_INDEX = 'UPDATE_Q_INDEX';